apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_ADMIN_URL: {{ printf "postgres://postgres:%s@%s:%v/%s" (.Values.secrets.dbAdminPassword | urlquery) .Values.db.host .Values.db.port .Values.db.name | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.githubWebhookSecret | quote }}
